#!/bin/sh
#
# build script for ml-antlr
#
# options:
#   -o image		-- specify the name of the heap image, "ml-antlr"
#			   is the default.

CMD=$0

ROOT="ml-antlr"
HEAP_IMAGE=""
SMLNJROOT=`pwd`/../..
BIN=${INSTALLDIR:-$SMLNJROOT}/bin
LIB=${INSTALLDIR:-$SMLNJROOT}/lib
BUILD=$BIN/ml-build
SML=$BIN/sml

#
# process command-line options
#
while [ "$#" != "0" ] ; do
    arg=$1
    shift
    case $arg in
	-o)
	    if [ "$#" = "0" ]; then
		echo "$CMD: must supply image name for -o option"
		exit 1
	    fi
	    HEAP_IMAGE=$1; shift
	    ;;
	*)
	    echo $CMD: invalid argument: $arg
	    exit 1
	    ;;
    esac
done

if [ "$HEAP_IMAGE" = "" ]; then
    HEAP_IMAGE="$ROOT"
fi

#
# Build the ml-antlr standalone program:
"$BUILD" sources.cm Main.main $HEAP_IMAGE

#
# Install CM support for ml-antlr (grm-ext.cm is currently turned off
# to avoid conflict with ml-yacc):
"$SML" -m \$smlnj/library-install.cm tool/ml-antlr-tool.cm ${LIB}
# "$SML" -m \$smlnj/library-install.cm tool/grm-ext.cm ${LIB}

exit 0
